"""
Map fine-grained menu category labels (Chinese / noisy) to 13 standardized buckets + Other.
Order of RULES matters: first matching keyword wins.
"""

from __future__ import annotations

# Canonical targets (for reports / consistency)
STANDARD_CATEGORIES = (
    "Appetizers & Starters",
    "Soups",
    "Salads & Cold Dishes",
    "Mains",
    "Pasta / Noodles / Rice",
    "Snacks & Small Bites",
    "Set Meals & Combos",
    "Sides & Accompaniments",
    "Desserts & Sweets",
    "Beverages (Non-Alcoholic)",
    "Alcohol & Cocktails",
    "Breakfast & Brunch",
    "Other",
)

# Exact overrides (optional): label string -> standard name
EXACT_MAP: dict[str, str] = {
    # Generic / non-food meta labels → Other
    "品項": "Other",
    "品 名": "Other",
    "品名": "Other",
    "品名 名": "Other",
    "項目": "Other",
    "單": "Other",
    "一份": "Other",
    "加價購": "Other",
    "開瓶費": "Other",
    "冷凍專區": "Other",
    "其 它": "Other",
    "其他類": "Other",
    # A la carte sections (avoid keyword "單點" — matches 沙拉、配菜單點)
    "單點": "Snacks & Small Bites",
    "單點區": "Snacks & Small Bites",
    "單點系列": "Snacks & Small Bites",
    "韓金單點": "Snacks & Small Bites",
    # Mixed / regional headings
    "港飲煎、烤、炸": "Mains",
    "宜蘭經典": "Mains",
    "餐點": "Set Meals & Combos",
    "多點滿足": "Set Meals & Combos",
    "冬季當歸": "Soups",
    "豆豆好健康": "Snacks & Small Bites",
    "豆豆吃嘴饞": "Snacks & Small Bites",
    # English headings
    "Beverages": "Beverages (Non-Alcoholic)",
    "Main": "Mains",
    "DESSERTS": "Desserts & Sweets",
    "Khane de Naal Naal. Salads.": "Salads & Cold Dishes",
}

# (keyword_tuple, standard_category) — first match wins
RULES: list[tuple[tuple[str, ...], str]] = [
    # --- Breakfast & Brunch (before 飯/麵 catch-alls) ---
    (
        (
            "BRUNCH",
            "活力蛋餅",
            "現烤吐司",
            "吐司蛋餅類",
            "招牌麵糊蛋餅",
            "豆豆烤燒餅",
            "豆豆蒸包子",
            "法式土司",
            "法國土司",
            "厚片系類",
            "捲餅",
            "蔬食捲餅",
        ),
        "Breakfast & Brunch",
    ),
    (
        (
            "吐司類",
            "吐司",
            "厚片",
            "蛋餅",
            "燒餅",
            "飯糰",
            "包子",
            "饅頭",
            "麵包",
            "法式麵包",
            "烘蛋",
        ),
        "Breakfast & Brunch",
    ),
    # --- Alcohol ---
    (
        (
            "啤酒",
            "紅酒",
            "白酒",
            "調酒",
            "精釀",
            "雞尾酒",
            "Alcohol",
            "酒精",
            "開瓶",
            "酒飲",
            "Craft Beer",
        ),
        "Alcohol & Cocktails",
    ),
    # --- Desserts (before generic 冰/茶) ---
    (
        (
            "甜點",
            "甜品",
            "甜、點心",
            "港式甜品",
            "嚐起來甜蜜蜜",
            "綿綿冰",
            "初夏下雪",
            "初夏好冰",
            "奶霜系列",
            "冰淇淋",
            "豆花",
        ),
        "Desserts & Sweets",
    ),
    # --- Beverages (non-alcoholic) ---
    (
        (
            "D渴找茶",
            "口渴找茶",
            "Herbal",
            "職人咖啡",
            "冰咖啡",
            "咖啡",
            "飲料",
            "飲品",
            "飲料 類",
            "其他飲品",
            "熱飲",
            "冰飲",
            "冷飲茶",
            "冷飲",
            "現泡茶",
            "養生茶品",
            "鮮奶茶",
            "鮮奶+茶",
            "特飲",
            "下午茶",
            "超值飲品",
            "茶飲",
            "果汁",
            "鮮果汁",
            "手拉港飲",
            "港飲",
            "湯飲",
            "Carbonated",
            "drinks",
            "ice",
        ),
        "Beverages (Non-Alcoholic)",
    ),
    # --- Salads & cold ---
    (
        ("沙拉", "冷盤", "冷食料理", "爽脆涼菜", "涼ㄟ", "涼皮", "輕食"),
        "Salads & Cold Dishes",
    ),
    # --- Pasta / Noodles / Rice (before Soups: 湯麵, 麵…) ---
    (
        (
            "義大利麵",
            "義大利",
            "燉飯",
            "湯麵類",
            "湯麵",
            "鍋燒",
            "烏龍",
            "丼飯",
            "丼",
            "生魚片丼",
            "炒飯",
            "炒飯/麵類",
            "炒飯/麵",
            "咖喱飯",
            "咖哩系列",
            "咖哩",
            "煎蛋飯",
            "乾麵類",
            "乾麵",
            "乾米粉",
            "米粉",
            "米食類",
            "恬味米食",
            "麵食類",
            "麵類",
            "麵 類",
            "飯類",
            "飯 類",
            "飯麵類",
            "麵.飯類",
            "飯/麵類",
            "就。很。飯麵",
            "魂之烏龍麵",
            "煸炒烏龍麵",
            "鍋燒/雞絲麵系列",
            "漢堡類",
            "MAIN COURSE",
            "MAIN",
            "主食類",
            "主食",
            "肉麵",
            "鴨肉麵",
            "義式",
            "羅勒",
            "蘿勒",
            "青醬",
            "紅醬",
            "白醬",
            "蒜香清炒",
            "經典肉醬",
            "獨家特色醬",
            "撒粉",
            "焗烤",
            "PASTAS",
            "RISOTTO",
            "麵線",
            "公仔麵",
        ),
        "Pasta / Noodles / Rice",
    ),
    # --- Set meals & combos ---
    (
        (
            "套餐類",
            "套餐",
            "超值套餐",
            "(任選二)",
            "任選",
            "組合",
            "雙人",
            "主餐加值升級",
            "加值",
            "升級",
            "超人氣組合",
            "兒童餐",
            "小朋友專屬",
            "便當",
            "定食",
        ),
        "Set Meals & Combos",
    ),
    # --- Appetizers & starters ---
    (
        (
            "APPETIZER",
            "TAPAS",
            "開胃小點",
            "開胃菜",
            "開胃前菜",
            "私房開胃菜",
            "開胃菜&小物",
            "前菜",
            "頭盤小食",
            "坦杜里美味前菜",
            "香港街坊小食",
            "餃",
            "抄手",
            "點心",
        ),
        "Appetizers & Starters",
    ),
    # --- Snacks & small bites ---
    (
        (
            "炸物",
            "炸類",
            "酥炸類",
            "經典炸物",
            "炸物點心",
            "揚げ物",
            "蔬食炸物",
            "小點",
            "單點/炸物",
            "鹹品",
        ),
        "Snacks & Small Bites",
    ),
    # --- Sides & accompaniments ---
    (
        (
            "小菜類",
            "小菜",
            "小 菜",
            "滷味",
            "鲁 味",
            "滷製品",
            "滷味/小菜",
            "配菜",
            "青菜類",
            "青菜",
            "時蔬",
            "蔬菜類",
            "豆腐類",
            "鮮菇類",
            "沙拉、配菜單點",
            "川燙",
        ),
        "Sides & Accompaniments",
    ),
    # --- Soups (after 湯麵 rules) ---
    (
        (
            "湯類",
            "湯品",
            "湯 類",
            "湯品類",
            "好 湘 湯 品",
            "波靚湯",
            "冬瓜系列",
            "燉品",
        ),
        "Soups",
    ),
    # --- Mains (broad cooked dishes) ---
    (
        (
            "主餐類",
            "主餐",
            "主菜",
            "熱炒類",
            "快炒類",
            "鐵板類",
            "鐵板三杯",
            "三杯 鐵板類",
            "各類現炒",
            "家常料理",
            "客家菜",
            "火鍋類",
            "鍋 物",
            "煲類",
            "海鮮料理",
            "海鮮類",
            "海鮮",
            "海產",
            "鮮魚料理",
            "清蒸海上鮮",
            "鱒魚類",
            "豬肉類",
            "牛肉之料理",
            "鴨 肉",
            "白肉料理",
            "鐵板",
            "招牌菜",
            "本店招牌",
            "人氣主打",
            "丸滿招牌菜",
            "招牌",
            "頭餐",
            "排餐",
            "海鮮類 排餐",
            "中餐類",
            "鮮魚",
            "肉類",
            "肉類 類",
            "海河鮮熱菜",
            "特色飯食",
            "經典飯食",
            "時蔬、素食、蛋",
            "素食",
            "蔬食餐",
            "握壽司",
            "壽司",
            "烤類",
            "石頭鍋",
            "燒酒麻香鍋",
            "剝皮辣椒鍋",
            "蒜爆蛤蜊鍋",
            "特色菜",
            "三杯香氣",
            "三杯類",
            "烤物",
            "奶香鍋",
            "麻辣鍋",
            "炙燒",
            "雙饗",
            "辦桌",
            "主廚推薦",
            "主廚",
            "陶盤",
        ),
        "Mains",
    ),
]


def standardize_category(raw: str) -> str:
    """Map one raw category label to a standard category name."""
    s = str(raw).strip()
    if not s:
        return "Other"

    if s in EXACT_MAP:
        return EXACT_MAP[s]

    sn = s.replace(" ", "").replace("\u3000", "")

    for keywords, cat in RULES:
        for kw in keywords:
            if kw in s or kw in sn:
                return cat

    return "Other"
